### ISSUE TITLE
Issue with Uploading Component to ESP Registry - Name Not Supported (PACMAN-892)

### ISSUE THREAD

**Issue by hayschan** [espressif/upload-components-ci-action#17]
Hello,

I'm encountering an issue while trying to use the `espressif/upload-components-ci-action` GitHub Action to upload a component to the ESP registry. The error indicates that the component's name is not supported in the registry, and the upload fails. The error is "Name is not supported for components in the registry".

Here are the details:

**Error Log:**

```python
Run espressif/upload-components-ci-action@v1
  with:
    namespace: hayschan
    name: AutoPID_for_ESP_IDF
    version: v1.0.1
    api_token: ***
    repository_url: git://github.com/hayschan/AutoPID-for-ESP-IDF.git
    commit_sha: 5ad04cc25b32e942eed4ab027c3cf33503214ec7
...
Processing 1 components
Processing component "AutoPID_for_ESP_IDF" at .
Saving archive to "/github/workspace/dist/AutoPID_for_ESP_IDF_1.0.1.tgz"
Uploading archive /github/workspace/dist/AutoPID_for_ESP_IDF_1.0.1.tgz

  0%|          | 0.00/12.0k [00:00<?, ?B/s]
 68%|██████▊   | 8.19k/12.0k [00:00<00:00, 21.4kB/s]
Wait for processing, it is safe to press CTRL+C and exit
                                                    

You can check the state of processing by running CLI command "compote component upload-status --job=bdac49f5-138b-4db4-8ad3-4b10f1afe623 "
  0%|          | 0/100 [00:00<?, ?%/s]
                                      
ERROR: Uploaded component wasn't processed successfully.
Name is not supported for components in the registry
Failed to upload the following components:
- hayschan/AutoPID_for_ESP_IDF
```

**GitHub Action YAML:**

```yaml
name: Upload component to ESP registry

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # This line enables manual triggering

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload component to the registry
        uses: espressif/upload-components-ci-action@v1
        with:
          namespace: "hayschan"
          name: "AutoPID_for_ESP_IDF"
          version: ${{ github.ref_name }}
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
```

**Questions:**

1. Is there a specific naming convention or restriction for component names in the ESP registry that I'm missing?
2. Have I misconfigured anything in the GitHub Action YAML file that could be causing this issue?
3. What steps can I take to resolve this error and successfully upload the component?

Any help or guidance would be greatly appreciated. Thank you!

Best regards,
Hays Chan
